name: Run Game Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Запуск каждые 6 часов
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Если у вас есть зависимости

      - name: Run bot with timeout
        run: |
          timeout 5h python your_bot.py  # Замените `your_bot.py` на имя вашего скрипта
